name: MacOS 10.15

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }} 
  BRANCH: "main"

jobs:

  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Wait and Early Trigger next workflow
        run: |
          # Waits 300 minutes 
          while ((${TIME_LEFT:=300} > 0)); do
            printf "Please wait %.f minutes ...\n" "${TIME_LEFT}"
            sleep 5m
            TIME_LEFT=$((TIME_LEFT - 5))
          done
          # Triggers same workflow before the other job finishes
          curl -X POST --header "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/mirror-bot.yml/dispatches -d '{"ref":"main"}'

  mirror:
    runs-on: macos-latest
    steps:
      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      - name: Setup docker
        run: |
          brew install -f -q --cask virtualbox
          brew install -f -q --formula docker docker
      - name: Setup VM
        run: |
          curl -sL https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso -o ~/Downloads/boot2docker.iso
          docker-machine create --driver virtualbox --virtualbox-memory "4096" --virtualbox-hostonly-cidr 192.168.56.1/21 --virtualbox-cpu-count=4 --virtualbox-disk-size=40960 --virtualbox-boot2docker-url ~/Downloads/boot2docker.iso default
          docker-machine env default
      - name: Clone The Secret Mirror Repository
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.MIRROR_REPOSLUG }} -b ${Branch} source
      - name: Compile The Mirroring Docker Container
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
          docker image ls
      - name: running Docker
        timeout-minutes: 340
        continue-on-error: true
        run: |
          docker run --privileged --rm -i mirror-bot
      - name: Loop Workflow
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
       

          docker-machine env default
      - name: Clone Repository
        run: |
          git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.MIRROR_REPOSLUG }} source
      - name: Compile The Mirroring Docker Container
        run: |
          cd source || exit 1
          git checkout $BRANCH
          eval $(docker-machine env default)
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
          docker image ls
      - name: Running mirror-bot In Docker
        timeout-minutes: 300
        continue-on-error: true
        run: |
          eval $(docker-machine env default)
          docker run --privileged --rm -i mirror-bot
